var selectableCarts = {
	platoon1:{
		squad1:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		squad2:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		squad3:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		tag:'squad',
		all:[]
	},
	platoon2:{
		squad1:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		squad2:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		squad3:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		tag:'squad',
		all:[]
	},
	platoon3:{
		squad1:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		squad2:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		squad3:{cart1:[],cart2:[],cart3:[],tag:'cart',all:[]},
		tag:'squad',
		all:[]
	},
	tag:'platoon',
	all:[]
};
